### ISSUE TITLE
Request for Assistance in Accessing the Relevant Code for the Hybrid Patch Retriever Module

### ISSUE THREAD

**Issue by JasmineSpace** [wang-weishi/RAP-Gen#1]
Dear Authors,

Sorry for interrupting you here with this issue.

I am recently reading the RAP-Gen paper, which presents a very cool idea for patch generation. I am trying to reproduce the experiments results, but it seems that there is no releavent part about the hybrid patch retriever component in both your code repository and the provided artifacts.

Accordingly, I cannot access the retrived results by RAP-Gen . It would be greatly appreciated if you could consider making this component publicly available in the repository.

I sincerely appreciate your time and assistance in this matter.

Yours,
Liupei

**Comment by wang-weishi** [comment]
https://github.com/salesforce/CodeT5/issues/146
 "We plan to release the finetuning scripts in the future if there are many asks for this."

-  We will only release the retriever training script if there is a demand from the research society.  
- You can access the retrieved results by RAP-Gen. Double-check the dataset_rapgen (i.e. tifix_rapgen), we use hybrid retriever for retrieving the top-1 bug fix patterns and then concatenate it with the source code for the model's encoder
